# Directorio central de reportes
serenity.outputDirectory = target/site/serenity

# Evitar errores de "Test Root: null" indicando la ruta relativa
serenity.test.root = features
serenity.requirements.dir = api-automation/src/test/resources/features

# Reporte detallado para ver los JSON
serenity.report.accessibility = true
serenity.console.colors = true
serenity.logging = VERBOSE

# Forzar a que reconozca los resultados del subproyecto
serenity.test.results.dir = target/site/serenity